INSERT INTO regions (region_name, code_2004, code_2013, code_2021)
VALUES ('AR Krym', 'AK', 'KK', 'TK'),
       ('Vinnytska oblast', 'AB', 'KB', 'IM'),
       ('Volynska oblast', 'AC', 'KC', 'CM'),
       ('Dnipropetrovska oblast', 'AE', 'KE', 'PP'),
       ('Donetska oblast', 'AH', 'KH', 'TH'),
       ('Zhytomyrska oblast', 'AM', 'KM', 'TM'),
       ('Zakarpatska oblast', 'AO', 'KO', 'MT'),
       ('Zaporizka oblast', 'AP', 'KP', 'TP'),
       ('Ivano-Frankivska oblast', 'AT', 'KT', 'TO'),
       ('Kyivska oblast', 'AI', 'KI', 'TI'),
       ('misto Kyiv', 'AA', 'KA', 'TT'),
       ('Kirovohradska oblast', 'BA', 'HA', 'XA'),
       ('Luhanska oblast', 'BB', 'HB', 'EP'),
       ('Lvivska oblast', 'BC', 'HC', 'CC'),
       ('Mykolaivska oblast', 'BE', 'HE', 'XE'),
       ('Odeska oblast', 'BH', 'HH', 'OO'),
       ('Poltavska oblast', 'BI', 'HI', 'XI'),
       ('Rivnenska oblast', 'BK', 'HK', 'XK'),
       ('Sumska oblast', 'BM', 'HM', 'XM'),
       ('Ternopilska oblast', 'BO', 'HO', 'XO'),
       ('Kharkivska oblast', 'AX', 'KX', 'XX'),
       ('Khersonska oblast', 'BT', 'HT', 'XT'),
       ('Khmelnytska oblast', 'BX', 'HX', 'OX'),
       ('Cherkaska oblast', 'CA', 'IA', 'OA'),
       ('Chernihivska oblast', 'CB', 'IB', 'OB'),
       ('Chernivetska oblast', 'CE', 'IE', 'OE'),
       ('misto Sevastopol', 'CH', 'IH', 'OH');
